<?php
/**
 * VirtualPayer_Cardnet Connect Plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   VirtualPayer
 * @package    VirtualPayer_Cardnet
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<fieldset class="form-list">
    <?php $_code=$this->getMethodCode() ?>
    
    <?php $redirect = Mage::getModel('cardnet/redirect'); ?>
     <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <?php echo $this->__('You will be redirected to Lloyds Cardnet secure Hosted Payment Page.') ?>
        </li>
    </ul>
</fieldset>